{
  "formatVersion": "1.1",
  "component": {
    "group": "com.formbuilder.sdk",
    "module": "formbuilder-sdk",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "formbuilder-sdk-1.1.5.aar",
          "url": "formbuilder-sdk-1.1.5.aar",
          "size": 1220929,
          "sha512": "3b74e2bc462a0933b9db35cb25aecea6e0019ef93e9b4c89b95abc3c827d9dba05a0da397b1c15801dc6bace458886a7d10522776e8b0fbd78d1e901e9ce41d2",
          "sha256": "27223f9a8e5d7c46a95af939ba9fa60d03c1c6e2a7bc413f710b6c16ad38e717",
          "sha1": "2898fa00b05a159f16f5765557da6188da93364b",
          "md5": "baec925ad5c7b91c36dcdc47619028f2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "formbuilder-sdk-1.1.5.aar",
          "url": "formbuilder-sdk-1.1.5.aar",
          "size": 1220929,
          "sha512": "3b74e2bc462a0933b9db35cb25aecea6e0019ef93e9b4c89b95abc3c827d9dba05a0da397b1c15801dc6bace458886a7d10522776e8b0fbd78d1e901e9ce41d2",
          "sha256": "27223f9a8e5d7c46a95af939ba9fa60d03c1c6e2a7bc413f710b6c16ad38e717",
          "sha1": "2898fa00b05a159f16f5765557da6188da93364b",
          "md5": "baec925ad5c7b91c36dcdc47619028f2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "formbuilder-sdk-1.1.5-sources.jar",
          "url": "formbuilder-sdk-1.1.5-sources.jar",
          "size": 223789,
          "sha512": "ca940a438df63d7a0d6bd52316d5cf7139ed875854820e74caa2ac569d543e1ad94a545bba17bf48f301edf253ab6886b43c464f87f4ad9540cbaba0f62edecd",
          "sha256": "f7604a0f0341f89d2dfb9da92c90cc609ee9233f2c19a47083f35961fae4ab50",
          "sha1": "e5f14a219a909f6b04186b6a20be38f57da13ec9",
          "md5": "fb3ca3031767250db940e267cd923f0e"
        }
      ]
    }
  ]
}
